In [31]:
import textstat
import math
import torch
from flair.embeddings import FlairEmbeddings
import pandas as pd

In [2]:
test_data = (
    "President George W Bush and his top advisers have warned the iraqi government that continuing funding for military elements of his new iraq strategy will be contingent on prime minister Nuri Kamal al-maliki's delivery on promises to quell violence, officials said."
)
print(textstat.automated_readability_index(test_data))

24.8

In [4]:
test_data2= ("""president bush and his top advisers , after nine days of unrelenting criticism from congress , are warning the iraqi government that continuing funding for an american troop increase and other elements of mr.""")
print(test_data2)

president bush and his top advisers , after nine days of unrelenting criticism from congress , are warning the iraqi government that continuing funding for an american troop increase and other elements of mr.

In [5]:
print(textstat.automated_readability_index(test_data2))

20.3

In [29]:
def ari(text):
    ari_text=textstat.automated_readability_index(text)
    
    return ari_text

In [27]:
def perplexity(text):
    
    model = FlairEmbeddings('news-forward').lm
    input = torch.tensor([model.dictionary.get_idx_for_item(char) for char in text[:-1]]).unsqueeze(1)

    # push list of character IDs through model
    hidden = model.init_hidden(1)
    prediction, _, hidden = model.forward(input, hidden)

    # the target is always the next character
    targets = torch.tensor([model.dictionary.get_idx_for_item(char) for char in text[1:]])

    # use cross entropy loss to compare output of forward pass with targets
    cross_entroy_loss = torch.nn.CrossEntropyLoss()
    loss = cross_entroy_loss(prediction.view(-1, len(model.dictionary)), targets).item()

    # exponentiate cross-entropy loss to calculate perplexity
    perplexity = math.exp(loss)

    return perplexity

In [30]:
text="""gov . eliot spitzer will preview his first executive budget in a speech on friday afternoon , laying out his plan to rein in medicaid and other health care spending , setting the stage for a battle with politically powerful health care providers and unions ."""


print(perplexity(text),ari(text))

2.234526759035803 23.4

START NYT_BERTSUmm

In [63]:
df_nyt=pd.read_csv("nyt_df_specificity_1.csv",decimal=',')

In [64]:
df_nyt.rename(columns = {'Hyponym summary specificity':'BertSumm summary specificity'}, inplace = True)

In [65]:
df_nyt

   BertSumm summary specificity T5 summary specificity
0            0.9999533758636953     0.8626342029217902
1            0.9999583309896132     0.9968107597000857
2            0.9977827040535602     0.9803213192946698
3            0.9995378017897648    0.28218781817183786
4            0.8788389835447071     0.8617973801801109
..                          ...                    ...
74           0.9967429758059348     0.9555464226123049
75          0.04385894714469191    0.13063543119490495
76           0.9711616067927823     0.2505305487127431
77           0.6777324887838287     0.4172190234608532
78           0.4595975271750691    0.33474996128338275

[79 rows x 2 columns]

In [66]:
nyt_ari=[]
nyt_perplexity=[]
wordcounts=[]
bertsym_nyt_file= open('79_nyt_orig_summ_new.txt','r')
for line in bertsym_nyt_file:
    nyt_ari.append(ari(line))
    nyt_perplexity.append(perplexity(line))
    words = line.split(' ')
    wordcounts.append(len(words))

In [68]:
df_nyt['BertSumm summary ari']=nyt_ari
df_nyt['BertSumm summary perplexity']=nyt_perplexity
df_nyt['BertSumm Sentence length']=wordcounts

In [69]:
df_nyt

,BertSumm summary specificity,T5 summary specificity,BertSumm summary ari,BertSumm summary perplexity,BertSumm Sentence length
0,0.9999533758636953,0.8626342029217902,34.8,2.581288,65
1,0.9999583309896132,0.9968107597000857,30.4,4.765846,61
2,0.9977827040535602,0.9803213192946698,23.6,2.227609,46
3,0.9995378017897648,0.28218781817183786,23.9,4.855034,56
4,0.8788389835447071,0.8617973801801109,13.8,2.576582,32
...,...,...,...,...,...
74,0.9967429758059348,0.9555464226123049,24.8,2.353609,48
75,0.04385894714469191,0.13063543119490495,11.6,2.619034,18
76,0.9711616067927823,0.2505305487127431,21.4,2.721666,35
77,0.6777324887838287,0.4172190234608532,15.5,2.912978,26
78,0.4595975271750691,0.33474996128338275,18.5,2.215448,20

In [70]:
nyt_ari=[]
nyt_perplexity=[]
wordcounts=[]
bertsym_nyt_file= open('79_t5_single_sentsum_new.txt','r')
for line in bertsym_nyt_file:
    nyt_ari.append(ari(line))
    nyt_perplexity.append(perplexity(line))
    words = line.split(' ')
    wordcounts.append(len(words))

In [71]:
df_nyt['T5 summary ari']=nyt_ari
df_nyt['T5 summary perplexity']=nyt_perplexity
df_nyt['T5 Sentence length']=wordcounts

In [72]:
df_nyt

,BertSumm summary specificity,T5 summary specificity,BertSumm summary ari,BertSumm summary perplexity,BertSumm Sentence length,T5 summary ari,T5 summary perplexity,T5 Sentence length
0,0.9999533758636953,0.8626342029217902,34.8,2.581288,65,13.8,2.483627,21
1,0.9999583309896132,0.9968107597000857,30.4,4.765846,61,22.9,4.476481,41
2,0.9977827040535602,0.9803213192946698,23.6,2.227609,46,21.8,2.522313,40
3,0.9995378017897648,0.28218781817183786,23.9,4.855034,56,8.5,20.281475,11
4,0.8788389835447071,0.8617973801801109,13.8,2.576582,32,14.4,3.387211,28
...,...,...,...,...,...,...,...,...
74,0.9967429758059348,0.9555464226123049,24.8,2.353609,48,16.1,3.033213,29
75,0.04385894714469191,0.13063543119490495,11.6,2.619034,18,13.1,2.422255,18
76,0.9711616067927823,0.2505305487127431,21.4,2.721666,35,14.2,2.321629,18
77,0.6777324887838287,0.4172190234608532,15.5,2.912978,26,14.6,3.848674,22
78,0.4595975271750691,0.33474996128338275,18.5,2.215448,20,18.1,2.462827,17

In [77]:
df_nyt.to_csv('Final_NYT_evaluation.csv',index= False)

START CNN

In [80]:
df_cnn=pd.read_csv("cnn_df_specificity_1.csv",delimiter=',')
df_cnn.rename(columns = {'Hyponym summary specificity':'BertSumm summary specificity'}, inplace = True)

In [81]:
df_cnn

    BertSumm summary specificity  T5 summary specificity
0                       0.556803                0.272329
1                       0.898384                0.885341
2                       0.767727                0.689314
3                       0.997705                0.963775
4                       0.930919                0.826275
..                           ...                     ...
89                      0.999788                0.939830
90                      0.972484                0.698058
91                      0.999005                0.177242
92                      0.894588                0.522512
93                      0.970400                0.941426

[94 rows x 2 columns]

In [82]:
cnn_ari=[]
cnn_perplexity=[]
wordcounts=[]
bertsym_cnn_file= open('94-cnn_orginal_summaries_single_sent.txt','r')
for line in bertsym_cnn_file:
    cnn_ari.append(ari(line))
    cnn_perplexity.append(perplexity(line))
    words = line.split(' ')
    wordcounts.append(len(words))

In [83]:
df_cnn['BertSumm summary ari']=cnn_ari
df_cnn['BertSumm summary perplexity']=cnn_perplexity
df_cnn['BertSumm Sentence length']=wordcounts

In [84]:
df_cnn

,BertSumm summary specificity,T5 summary specificity,BertSumm summary ari,BertSumm summary perplexity,BertSumm Sentence length
0,0.556803,0.272329,19.3,2.043181,28
1,0.898384,0.885341,17.8,2.880904,36
2,0.767727,0.689314,14.6,2.208308,26
3,0.997705,0.963775,21.1,3.093231,41
4,0.930919,0.826275,17.5,3.281255,32
...,...,...,...,...,...
89,0.999788,0.939830,29.2,2.701917,48
90,0.972484,0.698058,20.5,3.135321,36
91,0.999005,0.177242,25.9,3.381498,48
92,0.894588,0.522512,14.5,3.390701,29
93,0.970400,0.941426,16.8,3.494960,30

In [85]:
cnn_ari=[]
cnn_perplexity=[]
wordcounts=[]
bertsym_cnn_file= open('94-cnn_t5_single_sentsum.txt','r')
for line in bertsym_cnn_file:
    cnn_ari.append(ari(line))
    cnn_perplexity.append(perplexity(line))
    words = line.split(' ')
    wordcounts.append(len(words))

In [86]:
df_cnn['T5 summary ari']=cnn_ari
df_cnn['T5 summary perplexity']=cnn_perplexity
df_cnn['T5 Sentence length']=wordcounts

In [88]:
df_cnn.to_csv('Final_CNN_evaluation.csv',index= False)

PERPLEXITY OF T5

In [98]:
from transformers import AutoModelWithLMHead, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("mrm8488/t5-base-finetuned-summarize-news")
model = AutoModelWithLMHead.from_pretrained("mrm8488/t5-base-finetuned-summarize-news")

In [122]:
import numpy as np
def perplex(text, max_length=150):
    input_ids = tokenizer.encode(text, return_tensors="pt", add_special_tokens=True)
    labels = tokenizer(text, return_tensors="pt").input_ids

    generated_ids = model.generate(input_ids=input_ids, num_beams=2, max_length=max_length,  repetition_penalty=2.5, length_penalty=1.0, early_stopping=True)

    preds = [tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=True) for g in generated_ids]
    loss = model(input_ids=input_ids, labels=labels).loss
    loss=torch.exp(loss)
#     loss=loss.detach().numpy()[0]

    return loss.item()

In [123]:
text="""gov . eliot spitzer will preview his first executive budget in a speech on friday afternoon , laying out his plan to rein in medicaid and other health care spending , setting the stage for a battle with politically powerful health care providers and unions ."""


print(perplex(text))

1.4629520177841187

In [127]:
perp_nyt_bert=[]
bertsym_nyt_file= open('79_nyt_orig_summ_new.txt','r')
for line in bertsym_nyt_file:
    perp=perplex(line)
    perp_nyt_bert.append(perp)

In [128]:
perp_nyt_t5=[]
bertsym_nyt_file= open('79_t5_single_sentsum_new.txt','r')
for line in bertsym_nyt_file:
    perp=perplex(line)
    perp_nyt_t5.append(perp)

In [134]:
perp_cnn_bert=[]
bertsym_nyt_file= open('94-cnn_orginal_summaries_single_sent.txt','r')
for line in bertsym_nyt_file:
    perp=perplex(line)
    perp_cnn_bert.append(perp)

In [135]:
perp_cnn_t5=[]
bertsym_nyt_file= open('94-cnn_t5_single_sentsum.txt','r')
for line in bertsym_nyt_file:
    perp=perplex(line)
    perp_cnn_t5.append(perp)

In [136]:
df_perp = pd.DataFrame(list(zip(perp_nyt_bert, perp_nyt_t5,perp_cnn_bert,perp_cnn_t5)),
               columns =['perp_nyt_bert', 'perp_nyt_t5','perp_cnn_bert','perp_cnn_t5'])

In [137]:
df_perp

    perp_nyt_bert  perp_nyt_t5  perp_cnn_bert  perp_cnn_t5
0        1.534671     3.624126       2.195453     3.210437
1        2.236282     1.829370       1.952373     2.581090
2        1.595818     1.356422       1.827912     1.763938
3        2.049780     2.293283       1.666588     1.972001
4        1.825488     1.808036       2.026463     2.245075
..            ...          ...            ...          ...
74       2.015158     1.899739       2.255299     1.925460
75       3.531237     2.756215       1.846947     3.007367
76       2.028971     2.611960       1.757486     3.364413
77       2.080306     2.323627       1.588256     1.611247
78       1.887393     1.652632       1.879404     2.378981

[79 rows x 4 columns]

In [138]:
df_perp.describe()

       perp_nyt_bert  perp_nyt_t5  perp_cnn_bert  perp_cnn_t5
count      79.000000    79.000000      79.000000    79.000000
mean        2.030380     2.288607       1.974776     2.571284
std         0.411646     0.877790       0.298819     0.883812
min         1.534671     1.356422       1.421679     1.506601
25%         1.736077     1.820422       1.756181     1.915640
50%         1.968248     2.094930       1.958734     2.264678
75%         2.207911     2.348200       2.159529     3.090685
max         3.695912     6.569329       2.911489     6.023664